site_name: fgebhart/blog

site_url: https://blog.fgebhart.dev/
repo_url: https://github.com/fgebhart/blog
edit_uri: edit/main/docs/
repo_name: fgebhart/blog

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Ubuntu
  logo: assets/octopus.png
  favicon: assets/octopus.png
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - navigation.sections   # Disable sections once blog posts number increases
    - navigation.top

plugins:
  - search
  - awesome-pages
  - social
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  analytics:
    provider: google
    property: G-QDM5VJQE7E
  social:
    - icon: fontawesome/solid/address-book
      link: https://fgebhart.dev
      name: My website
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/FabianGebhart
      name: My twitter
    - icon: fontawesome/brands/github 
      link: https://github.com/fgebhart
      name: My github
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/fabian-gebhart/
      name: My linkedin

copyright: Copyright &copy; 2022 Fabian Gebhart
