name: Publish Blog
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Cache mkdocs .cache dir
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Deploy mkdocs to Github Pages
        run: poetry run mkdocs gh-deploy --force
